openapi: 3.0.0
info:
  title: Home Credit - Partner API - Future version
  version: ""
  description: >-
    API documentation for Home Credit API for partners (next release
    documentation).


    > Version of documentation: `1.2.2` (10/2023)


    | Version        | Release | Release date | News |

    | ---            | ---     | ---          | ---  |

    | 1.2.2 (10/2023) | CS110  | 24.10.2023   | New data in response of [search application](#reference/application-resources/application-operations/search-application) - details about who and where was contract created (`Salesroom`, `Salesman`, `Acquirer` in `OriginationContext` class) |

    | 1.2.1 (11/2021) | CS86   | 8.11.2021    | New filter parameters for method [search application](#reference/application-resources/application-operations/search-application) |

    | 1.1.1 | CS82    | 13.7.2021    | Initial version |


    ## Getting started


    This online document describes Home Credit (HC) API for partners - the means for partners through which they can get informations about client contracts with Home Credit.


    | Group of services                                           | Purpose                                                                                                                                                      |

    | ---                                                         | ---                                                                                                                                                          |

    | [Security](#reference/security)                             | Security rules and principles                                                                                                                                |

    | [Application resources](#reference/application-resources)   | Resources that allows getting information about *application* during its whole life cycle                                                                                |


    ### Basic implementation


    This API is very simple, partner should implement only this:

    1. [Login](#reference/security/login-partner)
        - Partner must be authorized to be able to access the most resources
    1. [Search application](#reference/application-resources/application-operations)
        - Partner uses this resource for getting all necessary data

    ## Documentation principles


    - attributes in request/response object are optional unless stated otherwise (`required` flag under attribute name)


    - a required attribute in an optional object means, that if an optional object is specified, it must contain the required attribute.


    - all values in request/response attributes are just examples, except for enum values - these are the only possible values for the given attribute.


    - documentation adheres to [semantic versioning](https://semver.org/spec/v2.0.0.html), which makes a distinction between *major*, *minor*, and *patch* versions.


    ### Naming conventions


    - we use camelCase for all object and attribute names


    - we use CAPITAL_UNDERSCORE for enum values


    - we use plural in resource names


    ### Key words used in this document (RFC 2119)


    The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt).


    ## Home Credit REST API principles


    ### Request restrictions


    Please, keep in mind following restrictions regarding requests:


    - Maximum request size is **10 MB**.


    - Maximum size of accepted single file is **500 kB**.


    - Here is the list of supported files:


    | MIME type                                                                 | Example(s)                 |

    | ---                                                                       | ---                        |

    | application/pdf                                                           | *.pdf                      |

    | application/vnd.openxmlformats-officedocument.spreadsheetml.sheet         | *.xlsx                     |

    | application/vnd.openxmlformats-officedocument.wordprocessingml.document   | *.docx                     |

    | application/vnd.openxmlformats-officedocument.presentationml.presentation | *.pptx                     |

    | application/vnd.ms-excel                                                  | *.xls, *.xlt, *.xla        |

    | application/msword                                                        | *.doc, *.dot               |

    | application/vnd.ms-powerpoint                                             | *.ppt, *.pot, *.pps, *.ppa |

    | plain/text                                                                | *.csv, *.txt               |

    | image/jpeg                                                                | *.jpg, *.jpeg              |

    | image/png                                                                 | *.png                      |

    | image/gif                                                                 | *.gif                      |


    ### API calls limits


    When partner reaches API calls limit (calls the API more times than is his quota), HTTP error 429 is returned. To inform about limits we use following response headers:


    - `X-Rate-Limit-Limit` - The number of allowed requests in the current period


    - `X-Rate-Limit-Remaining` - The number of remaining requests in the current period


    - `X-Rate-Limit-Reset` - The number of seconds left in the current period


    ### Versioning


    We use API version in URL (e.g. `https://api.homecredit.cz/customer/v1/my/profile`). *Minor* changes and *patches* (see below) that don't break backwards compatibility do NOT increase API version, e.g. they MAY happen without prior notice and your application should be ready to handle them.


    *Minor* changes include:


    - adding new resource


    - adding new optional header/URL parameter or optional body attribute to request


    - adding new attribute to response body


    - adding new error codes and messages, provided that error structure is the same


    ### Response encoding


    Unless stated otherwise, all responses are sent as `Content-Type: application/json; charset=utf-8`


    ### HTTP status codes


    We use following status codes throughout the API, except for OAuth flow when response codes are prescribed in RFC


    - 200 `OK` - request was successful


    - 201 `Created` - request was successful and resource was created


    - 202 `Accepted` - request has been accepted for processing, but the processing has not been completed


    - 204 `No Content` - we accepted partner's request but there is nothing to return (e.g. response is empty)


    - 400 `Bad Request` - syntax error, e.g. request is missing required parameters/attributes or parameter values are of incorrect type


    - 401 `Unauthorized` - partner is not authorized


    - 403 `Forbidden` - access denied (e.g. user / application is not allowed to use the resource)


    - 404 `Not Found` - resource could not be found


    - 405 `Method Not Allowed` - specified method is not allowed for resource


    - 422 `Unprocessable Entity` -  business (semantic) errors. Request is well-formed, but cannot be processed (e.g. payment due date is in past). Errors are specified in response body (see below)


    - 429 `Too Many Requests` - partner exceeded the rate limit (see section [API calls limit](#introduction/api-calls-limits) above)


    - 500 `Internal Server Error` - something went wrong on our side


    - 503 `Service Unavailable` - there is planned service outage


    ### Error handling


    Besides HTTP status codes, which are the main indication if something goes wrong, we also use `errors` object to report more details about errors.


    Errors object example:


    ```javascript

    {
        ...

        errors: [
            {
                "code": "ERR_100",
                "message": "Invalid contract number",
                "severity": "ERROR",
                "attribute": "partyAccount.accountNumber",          // optional
                "ticketId": "UAT1:AMS:20160516-091658.450:45e4" // optional
            },
            {
                "code": 352,
                "message": "Insufficiend funds for payment order realization",
                "severity": "WARN"
            },
            {
                "code": 523,
                "message": "This order will trigger currency exchange operation",
                "severity": "INFO"
            }
        ]
    }

    ```


    Error object attributes

    | Attribute name | Description                                                     |

    | ---            | ---                                                             |

    | code           | unique error code                                               |

    | message        | human readable error description (non-localized)                |

    | severity       | error severity (see below)                   |

    | attribute      | json path of request attribute that caused the error (optional) |

    | ticketId       | internal ticket ID, used for error backtracking                 |


    There are 3 levels of error severity:


    - `ERROR` - critical error, execution cannot continue. This MUST be indicated also by appropriate HTTP status code (e.g. `422 Unprocessable Entity`)


    - `WARN` - non-critical error, execution can continue but further user interaction is advisable (for request to proceed, partner MUST specify this error code in `override` request attribute). This MIGHT be indicated also by appropriate HTTP status code.


    - `INFO` - information only, execution can continue without user interaction.


    #### Errors overview


    | Status code | Code                  | Explanation                                                                     | Message                                                                                                        |

    | ---         | ---                   | ---                                                                             | ---                                                                                                            |

    | 400         | INVALID_REQUEST       | Request was not well formatted (malformed request syntax, size too large, etc.) | (*Various messages possible*) e.g. Unsupported combination of application state and order state                  |

    | 404         | OBJECT_NOT_FOUND      | The requested resource could not be found                                       | (*Various messages possible*) e.g. Specified object was not found                                              |

    | 422         | NOT_ALLOWED           | Operation is not allowed (internal reason)                                      | (*Various messages possible*) e.g. Not allowed (other reason)                                                    |

    | 500         | INTERNAL_SERVER_ERROR | Unexpected condition was encountered and no more specific message is suitable   | (*Various messages possible*) e.g. Failed to parse given JSON                                                  |


    ### Formats


    - **date** and **time** uses [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) formatting, e.g.:
      - date is represented as `YYYY-mm-dd`. Timezone (local) is added when necessary.
      - time is represented as `Thh:mm:ss`. Timezone is added when necessary. Time with arbitrary number of digits respresenting miliseconds is also accepted (when [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format criteria is met) but the time without miliseconds is always returned.
      - day of week is represented as number 1..7, with 1 being Monday
      - week no. 1 is the week with the year's first Thursday in it

    - **phone numbers** uses international mobile phone number format starting with '+' and including country code (example of valid number: `+420739111222`)


    - **numbers format** number format is defined by [JSON standard](http://www.json.org), e.g. decimals are separated by `.`


    - **money format** uses [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) formatting (in minor units, e.g.: 12590 in minor units represents 125,90 CZK/EUR)


    <!--

    ## Partial update

    We support partial update using PATCH method. Use JSON Merge Patch according to [RFC-7386](https://tools.ietf.org/html/rfc7386).

    -->
paths:
  /authentication/v2/partner:
    post:
      responses:
        "200":
          description: Partner acces token issued
          headers: {}
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/PartnerLoginResult"
              examples:
                response:
                  value:
                    accessToken: TokenForPartnerTokenForPartnerTokenForPartnerTokenForPartner
                    expiresIn: 7200
        "400":
          description: Unable to authenticate partner
          headers: {}
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/Errors"
              examples:
                response:
                  value:
                    errors:
                      - code: BAD_REQUEST
                        message: Bad request
                        severity: ERROR
                        attribute: Client.addresses[1].streetNumber
                        ticketId: UAT1:AMS:20160516-091658.450:45e4
      summary: Login partner
      operationId: Login partner
      description: >-
        Partner authenticate himself and obtain acces token with this resource.


        > **IMPORTANT NOTE:** Credentials for `/authentication/v1/partner` and  `/authentication/v2/partner` are not the same!
      tags:
        - Security
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Partner username
                password:
                  type: string
                  description: Partner secret password
              required:
                - username
                - password
              example:
                username: eShop
                password: eShopSecretPassword
  /partner/v1/applications:
    get:
      responses:
        "200":
          description: OK
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/SearchApplicationResponse"
              examples:
                response:
                  value:
                    data:
                      - id: 11200a0ee-adf54-dsa
                        status: CREATED
                        workflowSteps:
                          - code: DELIVERY
                            mandatory: true
                            priority: "1"
                        applicationCustomer:
                          firstName: John
                          lastName: Newborn
                          email: john.newborn@country.com
                          phone: "+420777123456"
                          addresses:
                            - streetAddress: Letenská
                              streetNumber: "22"
                              city: Prague
                              zip: 140 00
                              country: CZ
                              flags:
                                - PERMANENT
                        financedSubject:
                          type: ORDER
                          order:
                            number: "1234567890"
                            totalPrice:
                              value: 13300
                              currency: CZK
                            downPayment:
                              value: 13300
                              currency: CZK
                            variableSymbol: "1234567"
                            financing:
                              type: INSTALLMENT
                              installment:
                                productCode: COCONL06
                        contract:
                          number: "4066554400"
                          creditAmount:
                            value: 13300
                            currency: CZK
                          productCode: COCONL06
                        originationContext:
                          createdDate: 2018-01-16
                          salesroom:
                            code: "021574"
                            name: Naše prodejna, Uherské Hradiště
                            type: PHYSICAL
                          initiator:
                            firstName: Petr
                            lastName: Novák
                            partnerId: "1485"
                          salesman:
                            firstName: Petr
                            lastName: Novák
                            partnerId: "1485"
                          acquirer:
                            firstName: Jan
                            lastName: Novák
                            code: JN
                        services:
                          - type: INSURANCE
                            insurance:
                              code: IN1
        "400":
          description: Bad Request
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/Errors"
              examples:
                response:
                  value:
                    errors:
                      - code: BAD_REQUEST
                        message: Bad request
                        severity: ERROR
                        attribute: Client.addresses[1].streetNumber
                        ticketId: UAT1:AMS:20160516-091658.450:45e4
      summary: Search applications
      operationId: Search applications
      description: >-
        Partner may use resource `/partner/v1/applications` to check the state
        of partner's application and getting detailed information about it.
        Partner needs any identifier of application, either technical identifier
        of application (`applicationId` which is in the form of UUID),
        identifier of contract (human readable `contractNumber`) or
        `applicationKey` through which the search is performed over multiple
        (human readable) identifiers at once (it is typically used in face to
        face process with client who may not know which type of identifier he
        has).


        If the request was successfully processed, partner receives HTTP status code 200. If specified application was not found, empty data are returned.


        In other cases, partner receives one of the following errors:
          | Status code | Code                  | Explanation                                                                      |
          | ---         | ---                   | ---                                                                              |
          | 400         | INVALID_REQUEST       | Request was not well formatted (malformed request syntax, size too large, etc.)  |
          | 500         | INTERNAL_SERVER_ERROR | Unexpected condition was encountered and no more specific message is suitable    |

        + Parameters
          + applicationId: `11200a0ee-adf54-dsa` (string, optional) - Primary identifier of the application.
          + contractNumber: `4106554400` (string, optional) - Identifier of the contract. Used when the partner does not have the application identifier.
          + applicationKey: `4106554400` (string, optional) - Filter attribute through which the search is performed over multiple identifiers at once. Identifiers for contract number, application number (human readable attribute, not `applicationId`) or order number are used during the search. The use of this search attribute may cause a longer amount of time to complete the search and (in an extremely rare case) may return more than one application.
      tags:
        - Application resources
      parameters:
        - name: applicationId
          in: query
          description: Primary identifier of the application.
          required: false
          example: 11200a0ee-adf54-dsa
          schema:
            type: string
        - name: contractNumber
          in: query
          description: Identifier of the contract. Used when the partner does not have the
            application identifier.
          required: false
          example: "4106554400"
          schema:
            type: string
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              type: string
        description: Filter attribute through which the search is performed over
          multiple identifiers at once. Identifiers for contract number,
          application number (human readable attribute, not `applicationId`) or
          order number are used during the search. The use of this search
          attribute may cause a longer amount of time to complete the search and
          (in an extremely rare case) may return more than one application.
tags:
  - name: Security
    description: >-
      To access our API, partner have to obtain *access token* first; this token
      is a string of arbitrary length (30+ chars) and it has to be included in
      HTTP header to every request to API. This section describes way to obtain
      valid access token and use it to access protected resources.


      - to obtain access token, use `/authentication/v2/partner` resource with appropriate parameters (see the [`/authentication/v2/partner` resource documentation](#reference/security/login-partner))


      - access token should be present in every request using request header `Authorization`, with type `Bearer`. If access token has value `secret_token`, it should be specified as follows:


      `Authorization: Bearer secret_token`


      So the real example using curl will look like:


      ```

      curl -H "Authorization: Bearer secret_token" https://api.homecredit.cz/partner/v1/applications

      ```


      - access token has limited time validity (for 2 hours). After it is expired, partner has to obtain new one using `/authentication/v2/partner` resource.


      - if partner fails to specify access token `401 Unauthorized` error and following response body is returned:


      ```

      {
         "error_description": "The access token is missing",
         "error": "invalid_request"
      }

      ```


      - if partner provides invalid access token `401 Unauthorized` error and following response body is returned:


      ```

      {
          "error_description":"The access token is invalid or has expired",
          "error":"invalid_token"
      }

      ```


      > **IMPORTANT NOTE:** Partner must keep his access token and login credentials safe. Login credentials nor access token should NEVER be put into client page. If partner plans to integrate API calls in client flow without submitting the page to server, he should implement REST endpoint bound to his shopping basket session, that will be used as a proxy to call HC API.


      > NEVER transfer access token nor login credentials over plain HTTP. Such requests will be refused.
  - name: Application resources
servers:
  - url: https://api.homecredit.cz
components:
  schemas:
    SearchApplicationResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Application"
          description: Collection of found applications. If no application was found, data
            contains empty array
    ApplicationBase:
      type: object
      required:
        - id
        - status
      properties:
        id:
          type: string
          example: 11200a0ee-adf54-dsa
          description: Unique identifier in Home Credit
        status:
          type: string
          enum:
            - CREATED
            - PRESCORED
            - APPROVED
            - VERIFICATION
            - ALTERNATIVE
            - CONFIRMED
            - REJECTED
            - CANCELLED
          description: Application state.
        workflowSteps:
          type: array
          items:
            $ref: "#/components/schemas/WorkflowStep"
          description: Collection of application process actions available for current
            application state.
    Application:
      allOf:
        - $ref: "#/components/schemas/ApplicationBase"
        - type: object
          required:
            - financedSubject
            - originationContext
          properties:
            applicationCustomer:
              $ref: "#/components/schemas/ApplicationCustomerBase"
            financedSubject:
              $ref: "#/components/schemas/FinancedSubjectMinimal"
            contract:
              $ref: "#/components/schemas/Contract"
            originationContext:
              $ref: "#/components/schemas/OriginationContext"
            services:
              type: array
              items:
                $ref: "#/components/schemas/Service"
              description: Additional services agreed for the application (for example
                insurance)
    ApplicationCustomerBase:
      type: object
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
          example: John
          description: Customer first (given) name.
        lastName:
          type: string
          example: Newborn
          description: Customer last (family) name.
        email:
          type: string
          example: john.newborn@country.com
          description: E-mail address of customer.
        phone:
          type: string
          example: "+420777123456"
          description: Phone number with country code (including leading `+`)
        addresses:
          type: array
          items:
            $ref: "#/components/schemas/Address"
          description: Addresses.
    Address:
      type: object
      required:
        - streetAddress
        - streetNumber
        - city
        - zip
        - country
        - flags
      properties:
        streetAddress:
          type: string
          example: Letenská
          description: Street/city part
        streetNumber:
          type: string
          example: "22"
          description: Street number
        city:
          type: string
          example: Prague
          description: City
        zip:
          type: string
          example: 140 00
          description: Postal code
        country:
          type: string
          example: CZ
          description: Customer's country, [ISO 3166-1 format, subtype
            ALPHA-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). This
            means two letters in uppercase.
        flags:
          type: array
          items:
            $ref: "#/components/schemas/AddressFlag"
          description: Types of the address.
    AddressFlag:
      type: string
      enum:
        - PERMANENT
        - CONTACT
    OriginationContext:
      type: object
      required:
        - createdDate
        - salesroom
      properties:
        createdDate:
          type: string
          example: 2018-01-16
          description: Date the application has been created
        salesroom:
          $ref: "#/components/schemas/SalesroomOriginationContext"
        initiator:
          $ref: "#/components/schemas/Salesman"
        salesman:
          $ref: "#/components/schemas/Salesman"
        acquirer:
          $ref: "#/components/schemas/Acquirer"
    SalesroomOriginationContext:
      type: object
      required:
        - code
        - name
        - type
      properties:
        code:
          type: string
          example: "021574"
          description: Identifier of salesroom
        name:
          type: string
          example: Naše prodejna, Uherské Hradiště
        type:
          type: string
          enum:
            - PHYSICAL
            - ONLINE
            - PHONE
          description: Type of salesroom
    Salesman:
      type: object
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
          example: Petr
        lastName:
          type: string
          example: Novák
        partnerId:
          type: string
          example: "1485"
          description: Unique identifier of partner's salesman in partner's system, filled
            into Home Credit database during the registration of a new salesman
            (if provided).
    Acquirer:
      type: object
      required:
        - code
      properties:
        firstName:
          type: string
          example: Jan
        lastName:
          type: string
          example: Novák
        code:
          type: string
          example: JN
          description: Any string value filled in during the origination process.
    FinancedSubjectAbstract:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - ORDER
          description: Type of financed subject
    FinancedSubjectMinimal:
      allOf:
        - $ref: "#/components/schemas/FinancedSubjectAbstract"
        - type: object
          properties:
            order:
              $ref: "#/components/schemas/OrderMinimal"
    OrderMinimal:
      type: object
      required:
        - totalPrice
      properties:
        number:
          type: string
          example: "1234567890"
          description: Identifier, specified by the partner (e-shop, POS shop), if provided
        totalPrice:
          $ref: "#/components/schemas/Amount"
        downPayment:
          $ref: "#/components/schemas/Amount"
        variableSymbol:
          type: string
          example: "1234567"
          description: Variable symbol (internal for partner) for reconciliation payment,
            if provided
        financing:
          $ref: "#/components/schemas/OrderFinancing"
    Contract:
      type: object
      required:
        - number
        - creditAmount
        - productCode
      properties:
        number:
          type: string
          example: "4066554400"
          description: Unique identifier of contract
        creditAmount:
          $ref: "#/components/schemas/Amount"
        productCode:
          type: string
          example: COCONL06
          description: Product code
    OrderFinancing:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - INSTALLMENT
          description: Financing type
        installment:
          $ref: "#/components/schemas/Installment"
    Installment:
      type: object
      properties:
        productCode:
          type: string
          example: COCONL06
          description: Product code of installment program.
    Service:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - INSURANCE
          description: Service type
        insurance:
          $ref: "#/components/schemas/Insurance"
    Insurance:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          example: IN1
          description: Maximal available credit amount
    WorkflowStep:
      type: object
      required:
        - code
        - mandatory
        - priority
      properties:
        code:
          type: string
          enum:
            - DELIVERY
            - DELIVERED
          description: Workflow code
        mandatory:
          type: boolean
          example: true
          description: Workflow step may be optional (some additional services available
            for client) or required (scoring, contract signature etc.)
        priority:
          type: string
          example: "1"
          description: Identifier of workflow step's priority expressed as number (lowest
            number means highest priority)
    Error:
      type: object
      required:
        - code
        - message
        - severity
      properties:
        code:
          type: string
          example: BAD_REQUEST
          description: Unique internal error code
        message:
          type: string
          example: Bad request
          description: Human readable error description (non-localized)
        severity:
          type: string
          enum:
            - ERROR
            - WARN
            - INFO
        attribute:
          type: string
          example: Client.addresses[1].streetNumber
          description: JSON path of request attribute that caused the error (if applicable)
        ticketId:
          type: string
          example: UAT1:AMS:20160516-091658.450:45e4
          description: Internal ticket ID, used for error backtracking
    Errors:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/Error"
          description: Array with errors
    OTPErrors:
      allOf:
        - $ref: "#/components/schemas/Errors"
        - type: object
          properties:
            blockedUntil:
              type: string
              example: 2017-01-18T10:34:44+01:00
              description: requested operation is blocked until specified time
    PagingInfo:
      type: object
      required:
        - itemsPerPage
      properties:
        itemsPerPage:
          type: number
          example: 10
          description: number of items per page
        nextPage:
          type: string
          example: transactions?sort=category&limit=10&after=30
          description: request to retrieve next page, if it exists and can be
            unambiguously specified
        prevPage:
          type: string
          example: transactions?sort=category&limit=10&before=21
          description: request to retrieve previous page, if it exists and can be
            unambiguously specified
    Amount:
      type: object
      required:
        - value
        - currency
      properties:
        value:
          type: number
          example: 13300
          description: Amount in minor units (13300 represents 133) [ISO
            4217](https://en.wikipedia.org/wiki/ISO_4217)
        currency:
          type: string
          example: CZK
          description: Amount currency [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
            Only local currency is allowed (CZK in Czech Republic and EUR in
            Slovakia).
    VatAmount:
      type: object
      required:
        - value
        - currency
        - vatRate
      properties:
        value:
          type: number
          example: 14950
          description: Amount in minor units (14950 represents 149,50) [ISO
            4217](https://en.wikipedia.org/wiki/ISO_4217). MUST be 0 or greater.
        currency:
          type: string
          example: CZK
          description: Amount currency [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
            Only local currency is allowed (CZK in Czech Republic and EUR in
            Slovakia).
        vatRate:
          type: number
          example: 15
          description: VAT rate as natural number (15 represents 15% rate)
    File:
      type: object
      required:
        - filename
      properties:
        filename:
          type: string
          example: iphone6s.jpg
          description: File name.
    EmptyRE:
      type: object
      properties: {}
    KeyValue:
      type: object
      required:
        - key
        - value
      properties:
        key:
          type: string
          example: property
          description: Key
        value:
          type: string
          example: value
          description: Value
    BankAccount:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - IBAN
            - NATIONAL
          description: Account type
    AccountIBAN:
      type: object
      required:
        - iban
      properties:
        iban:
          type: string
          example: CZ6508000000192000145399
          description: Account number in IBAN format
    AccountNational:
      type: object
      required:
        - accountNumber
        - bankCode
      properties:
        prefix:
          type: string
          example: "000000"
          description: Account number prefix. For domestic accounts, this will be
            specified in national format.
        accountNumber:
          type: string
          example: "1235335010"
          description: Account number. For domestic accounts, this will be specified in
            national format.
        bankCode:
          type: string
          example: "3030"
          description: For domestic accounts, bank code in national format
    PhoneNumber:
      type: object
      required:
        - number
      properties:
        number:
          type: string
          example: "+420123456789"
          description: Phone number (including country code)
    Email:
      type: object
      required:
        - address
      properties:
        address:
          type: string
          example: darth.vader@empire.sw
          description: Email address
    PartnerLogin:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: eShop
          description: Partner username
        password:
          type: string
          example: eShopSecretPassword
          description: Partner secret password
    PartnerLoginResult:
      type: object
      required:
        - accessToken
      properties:
        accessToken:
          type: string
          example: TokenForPartnerTokenForPartnerTokenForPartnerTokenForPartner
          description: Access token
        expiresIn:
          type: number
          example: 7200
          description: Token validity remaining time (in seconds)
    AgentLoginRequest:
      type: object
      required:
        - clientId
        - authorizations
      properties:
        clientId:
          type: string
          example: MyCoolApplication
          description: Id of consumer
        authorizations:
          type: array
          items:
            $ref: "#/components/schemas/AgentLoginAuthorization"
          description: Array of authorization request.
    AgentLoginAuthorization:
      type: object
      required:
        - type
        - credentials
      properties:
        type:
          type: string
          enum:
            - CREDENTIALS
          description: Type of authorization requests
        credentials:
          $ref: "#/components/schemas/Credentials"
    Credentials:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: tester
          description: Agent's username
        password:
          type: string
          example: heslo123
          description: Agent's password
    AgentLoginResponse:
      type: object
      required:
        - token
      properties:
        token:
          $ref: "#/components/schemas/Token"
    Token:
      type: object
      required:
        - accessToken
        - tokenType
      properties:
        accessToken:
          type: string
          example: TokenForPartnerTokenForPartnerTokenForPartnerTokenForPartner
          description: Access token
        tokenType:
          type: string
          example: bearer
        expiresIn:
          type: number
          example: 43200
          description: Token validity remaining time (in seconds)
    AgentSetPasswordRequest:
      type: object
      required:
        - password
        - authorizations
      properties:
        password:
          type: string
          example: AgentSecretPassword
          description: New password for agent
        authorizations:
          type: array
          items:
            $ref: "#/components/schemas/AgentLoginAuthorization"
          description: Array of authorization request
    TokenCodeRequest:
      type: object
      required:
        - grant_type
        - client_id
        - client_secret
      properties:
        grant_type:
          type: string
          enum:
            - authorization_code
            - refresh_token
          description: Grant flow type, only `authorization_code` and `refresh_token` is
            supported
        client_id:
          type: string
          example: my_app_id
          description: "`client_id` parameter of partner's application, received at
            application registration"
        client_secret:
          type: string
          example: my_app_secret
          description: "`client_secret` parameter of partner's application, received at
            application registration"
    TokenResponse:
      type: object
      required:
        - token_type
        - access_token
        - expires_in
      properties:
        refresh_token:
          type: string
          example: 7dbadd74c434439db4fc9b2bbf8cabb3
          description: refresh token, if supported
        token_type:
          type: string
          example: bearer
          description: token type. Always "bearer".
        access_token:
          type: string
          example: ccafe62cbce645ce95b2acce839f4acc
          description: access token, to be included in API request
        expires_in:
          type: number
          example: 7200
          description: access token validity, in seconds
    AgentAccount:
      type: object
      required:
        - name
        - lastName
      properties:
        name:
          type: string
          example: Jiří
          description: User's first name.
        lastName:
          type: string
          example: Novák
          description: User's last name.
        salesrooms:
          type: array
          items:
            $ref: "#/components/schemas/Salesroom"
          description: List of salesrooms for which user is registered.
    Salesroom:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          example: "007"
          description: Salesroom's code
        name:
          type: string
          example: Testovací prodejna - Londýnské náměstí, Brno
          description: Salesroom's name
    Login_partner: {}
    Application_operations: {}
